# -*- coding: utf-8 -*-
"""pizzasiparissistemi.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ueq29mak9bFfRt9aFCbeNzwWV49Wm9cW
"""

import csv  ##veritabanı sistemi ve tarih saat için kullanacağımız kitaplıkların içe aktarımı
import datetime

with open("Orders_Database.csv", 'w') as file_csv:
    writer = csv.writer(file_csv)
    writer.writerow(["Time", "Description", "Cost", "Name", "Identity Number", "Credit Card Number","Credit Card Password"])
file = open('Menu.txt','w')

file.write('Menü:\n1: Klasik\n2: Margarita\n3: TürkPizza\n4: Sade Pizza\n*Ekstra malzemeler:\n1: Zeytin\n2: Mantarlar\n3: Keçi Peyniri\n4: Et\n5: Soğan\n6: Mısır\n Teşekkür ederiz!')
file.close()
#Üst Sınıf
class Pizza:
    def get_cost(self): #pizza çeşitleri için süper sınıf
        pass            #pizza açıklamaları ve pizza fiyatları için yöntemler oluşturma
    
    def get_description(self):
        pass


 #Alt Sınıf    
class Klasik (Pizza):          #pizza üst sınıfı için alt sınıf
    def get_description(self): #süpersınıfta oluşturduğumuz metotların kullanımı
      return "Klasik Pizza : Pizza sosu, Mozarella peyniri, Mantar, Zeytin, Salam"

    def get_cost(self):
      return 150

class Margarita (Pizza):
    def get_description(self):
       return "Margarita Pizza: Pizza sosu, Mozarella peyniri"

    def get_cost(self):
       return 100

class TurkPizza(Pizza):
    def get_description(Pizza):
      return "Türk Pizza: Pizza sosu, Margarita peyniri, Sucuk"

    def get_cost(Pizza):
      return 200

class SadePizza(Pizza):
    def get_description(self):
       return "Sade Pizza: Pizza Sosu" 

    def get_cost(Pizza):
       return 120 

 
class sos(Pizza): # soslar için bir üst sınıf oluşturma
    def __init__(self, pizza):
        self.pizza = pizza
    
    def get_cost(self): #başlık isimleri ve fiyatları için methodlar oluşturma
        return self.pizza.get_cost()
    
    def get_description(self):
        return self.pizza.get_description()

class Zeytin(sos):  #her malzeme için bir alt sınıf oluşturma
    def __init__(self, pizza):
        super().__init__(pizza)
        self.cost = 6
        self.description = "Zeytin"
    
    def get_cost(self): #her bir üst malzeme için yöntemleri kullanma
        return self.pizza.get_cost() + self.cost
    
    def get_description(self):
        return self.pizza.get_description() + ", " + self.description

class Mantar(sos):
    def __init__(self, pizza):
        super().__init__(pizza)
        self.cost = 7.50
        self.description = "Mantar"
    
    def get_cost(self):
        return self.pizza.get_cost() + self.cost
    
    def get_description(self):
        return self.pizza.get_description() + ", " + self.description
        
class KeciPeyniri(sos):
    def __init__(self, pizza):
        super().__init__(pizza)
        self.cost = 12.50
        self.description = "Keçi Peyniri"
    
    def get_cost(self):
        return self.pizza.get_cost() + self.cost
    
    def get_description(self):
        return self.pizza.get_description() + ", " + self.description

class Et(sos):
    def __init__(self, pizza):
        super().__init__(pizza)
        self.cost = 25.50
        self.description = "Et"
    
    def get_cost(self):
        return self.pizza.get_cost() + self.cost
    
    def get_description(self):
        return self.pizza.get_description() + ", " + self.description
        
class Sogan(sos): 
    def __init__(self, pizza):
        super().__init__(pizza)
        self.cost = 6.50
        self.description = "Soğan"
    
    def get_cost(self):
        return self.pizza.get_cost() + self.cost
    
    def get_description(self):
        return self.pizza.get_description() + ", " + self.description

class Misir(sos):
    def __init__(self, pizza):
        super().__init__(pizza)
        self.cost = 4.50
        self.description = "Mısır"
    
    def get_cost(self):
        return self.pizza.get_cost() + self.cost
    
    def get_description(self):
        return self.pizza.get_description() + ", " + self.description

def main(): #sipariş sistemimiz için bir main fonksiyon oluşturma
    print('Lütfen adınızı girin: ') #kişisel verilerin kullanıcıdan alınması
    isim = input()
    print('Lütfen TC kimlik numaranızı girin: ')
    tc = input()
    print('Lütfen kredi kartı numaranızı girin: ')
    k_numara = input()
    print('Lütfen kredi kartı sifrenizi girin: ')
    k_sifre = input()

    file = open('Menu.txt', 'r') #bir menü dosyası oluşturma ve bu dosyanın içine menüyü yazma
    print(file.read())           #menünün yazdırılması
    print("Lütfen bir pizza seçiniz.")
    pizza_choice = int(input())

    pizza = None

    if pizza_choice == 1: #her pizza türü için bir if-else koşulu oluşturma
         pizza = Klasik()

    elif pizza_choice == 2:
         pizza = Margarita()

    elif pizza_choice == 3:
         pizza = TurkPizza()

    elif pizza_choice == 4:
         pizza = SadePizza()          
     
    else:
         print("Invalid choice")
         return

    while True:
         print("Lütfen bir ekstra malzeme seçiniz. Seçiminiz tamamlanınca çıkmak için 7'ye basınız.")

         topping_choice = int(input()) # kullanıcıdan seçim verilerini almak
         if topping_choice == 1:       #her  topping type için bir if-else koşulu oluşturma
             pizza = Zeytin(pizza)

         elif topping_choice == 2:
             pizza = Mantar(pizza)
         
         elif topping_choice == 3:
             pizza = KeciPeyniri(pizza)   

         elif topping_choice == 4:
              pizza = Et(pizza)

         elif topping_choice == 5:
              pizza = Sogan(pizza)

         elif topping_choice == 6:
              pizza = Misir(pizza)              

         elif topping_choice == 7:
             break

         else:
             print("Invalid choice")


    print("Your pizza:")
    print(pizza.get_description()) # toplam siparişi hesaplama
    print("Toplam Fiyat: ₺", pizza.get_cost()) # toplam sipariş tutarını hesaplama
    
    with open("Orders_Database.csv", 'a') as file_csv: #kullanıcı bilgilerinin ve pizza seçeneklerinin girilmesi ve veri tabanına eklenmesi
        writer = csv.writer(file_csv)
        writer.writerow([datetime.datetime.now(), pizza.get_description(), pizza.get_cost(), isim, tc, k_numara,k_sifre])
       
        now = datetime.datetime.now()

        print ("Afiyet Olsun\n,Sipariş Tarihi : ")
        print (now.strftime("%Y-%m-%d %H:%M:%S")) # sipariş zamanının yazdırılması

main() #sipariş sistemini başlatmak için main fonksiyonu çağırılması